---
version: "3.3"
services:
  jenkins:
    container_name: jenkins
    image: "jenkins/jenkins:${JENKINS_TAG}"
    labels:
     - "traefik.enable=true"
     - "traefik.port=8080"
     - "traefik.http.routers.jenkins.rule=Host(`${JENKINS_HOST}`)"
     - "traefik.http.routers.jenkins.entrypoints=jenkins"
    privileged: true
    user: root
    restart: unless-stopped
    volumes:
     - "${JENKINS_VOLUME}/jenkins_home:/var/jenkins_home"
     - /var/run/docker.sock:/var/run/docker.sock
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.jenkins.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    depends_on:
    - jenkins