---
version: "3.3"
services:

  db:
    container_name: dbunittests
    image: "${MYSQL_IMAGE}:${MYSQL_TAG}"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "${DB_VOLUME}:/var/lib/mysql:rw"
    ports:
      - "3306:3306"

  jenkins:
    container_name: jenkins
    image: "${JENKINS_IMAGE}:${JENKINS_TAG}"
    labels:
     - "traefik.enable=true"
     - "traefik.port=8080"
     - "traefik.http.routers.jenkins.rule=Host(`${JENKINS_HOST}`)"
     - "traefik.http.routers.jenkins.entrypoints=jenkins"
    environment:
     - JENKINS_HOME=${JENKINS_VOLUME}/jenkins_home
     - JENKINS_JAVA_OPTS="-Djava.io.tmpdir=${JENKINS_VOLUME}/jenkins_home/tmp"
     - JAVA_OPTS="-Djava.io.tmpdir=${JENKINS_VOLUME}/jenkins_home/tmp
    privileged: true
    user: root
    restart: unless-stopped
    volumes:
     - "${JENKINS_VOLUME}/jenkins_home:/var/lib/jenkins" #for backward compatibility with VMs
     - "${JENKINS_VOLUME}/jenkins_home:${JENKINS_VOLUME}/jenkins_home"
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/bin/docker
     - /root/.docker/config.json:/root/.docker/config.json

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.jenkins.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    depends_on:
    - jenkins
  