--- 
version: "3"
services: 
  jenkins: 
    container_name: jenkins
    image: "jenkins/jenkins:lts-jdk11"
    ports: 
      - "80:8080"
      - "50000:50000"
    privileged: true
    user: root
    volumes: 
     - ~/jenkins_configuration:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/local/bin/docker:/usr/local/bin/docker 
